<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class BoardgameSeeder extends Seeder
{
    public function run()
    {
        DB::table('boardgames')->insert([
            [
                'title' => 'Silencio',
                'author' => 'Sebastiem Caiveau',
                'price' => 7,
                'publish_date' => '2020-01-01',
                'url' => 'https://example.com/silencio',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 12,
                'AgeRange' => '10+',
                'NoOfPlayers' => '2-4',
                'Theme' => 'Mystery',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A quiet cooperative card game where players must communicate without speaking.',
                'image_link' => 'https://example.com/images/silencio.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Patchwork',
                'author' => 'Uwe Rosenberg',
                'price' => 15,
                'publish_date' => '2014-05-10',
                'url' => 'https://example.com/patchwork',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 8,
                'AgeRange' => '8+',
                'NoOfPlayers' => '2',
                'Theme' => 'Crafting',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A two-player tile-laying game about sewing the most efficient quilt.',
                'image_link' => 'https://example.com/images/patchwork.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cafe Fatal',
                'author' => 'Brett J. Gilbert',
                'price' => 8,
                'publish_date' => '2017-03-15',
                'url' => 'https://example.com/cafe-fatal',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 5,
                'AgeRange' => '7+',
                'NoOfPlayers' => '3-6',
                'Theme' => 'Food',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A fast-paced dice game where players compete for pastries in a chaotic café.',
                'image_link' => 'https://example.com/images/cafe-fatal.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Overload',
                'author' => 'Wolfand Riedl',
                'price' => 20,
                'publish_date' => '2019-09-01',
                'url' => 'https://example.com/overload',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 10,
                'AgeRange' => '12+',
                'NoOfPlayers' => '2-5',
                'Theme' => 'Adventure',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A push-your-luck racing game where players risk overload to move faster.',
                'image_link' => 'https://example.com/images/overload.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Catan',
                'author' => 'Klaus Teuber',
                'price' => 25,
                'publish_date' => '1995-01-01',
                'url' => 'https://example.com/catan',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 20,
                'AgeRange' => '10+',
                'NoOfPlayers' => '3-4',
                'Theme' => 'Strategy',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A classic resource-trading game where players build settlements and roads.',
                'image_link' => 'https://example.com/images/catan.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Azul',
                'author' => 'Michael Kiesling',
                'price' => 30,
                'publish_date' => '2017-06-01',
                'url' => 'https://example.com/azul',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 14,
                'AgeRange' => '8+',
                'NoOfPlayers' => '2-4',
                'Theme' => 'Abstract',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A tile-drafting game inspired by Portuguese ceramic art.',
                'image_link' => 'https://example.com/images/azul.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ticket to Ride',
                'author' => 'Alan R. Moon',
                'price' => 40,
                'publish_date' => '2004-04-01',
                'url' => 'https://example.com/ticket-to-ride',
                'status' => 'active',
                'availabilityYN' => false,
                'inventoryCount' => 18,
                'AgeRange' => '8+',
                'NoOfPlayers' => '2-5',
                'Theme' => 'Travel',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A cross-country train adventure where players claim railway routes.',
                'image_link' => 'https://example.com/images/ticket-to-ride.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Carcassonne',
                'author' => 'Klaus-Jürgen Wrede',
                'price' => 35,
                'publish_date' => '2000-10-01',
                'url' => 'https://example.com/carcassonne',
                'status' => 'active',
                'availabilityYN' => false,
                'inventoryCount' => 16,
                'AgeRange' => '7+',
                'NoOfPlayers' => '2-5',
                'Theme' => 'Medieval',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A tile-placement game where players build cities, roads, and fields.',
                'image_link' => 'https://example.com/images/carcassonne.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Splendor',
                'author' => 'Marc André',
                'price' => 32,
                'publish_date' => '2014-03-01',
                'url' => 'https://example.com/splendor',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 11,
                'AgeRange' => '10+',
                'NoOfPlayers' => '2-4',
                'Theme' => 'Economy',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A fast-paced engine-building game about collecting gems and prestige.',
                'image_link' => 'https://example.com/images/splendor.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Wingspan',
                'author' => 'Elizabeth Hargrave',
                'price' => 60,
                'publish_date' => '2019-03-08',
                'url' => 'https://example.com/wingspan',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 9,
                'AgeRange' => '10+',
                'NoOfPlayers' => '1-5',
                'Theme' => 'Nature',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A relaxing engine-builder about attracting birds to your wildlife preserve.',
                'image_link' => 'https://example.com/images/wingspan.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Terraforming Mars',
                'author' => 'Jacob Fryxelius',
                'price' => 55,
                'publish_date' => '2016-09-01',
                'url' => 'https://example.com/terraforming-mars',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 22,
                'AgeRange' => '12+',
                'NoOfPlayers' => '1-5',
                'Theme' => 'Sci-Fi',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A deep engine-building game about developing Mars into a habitable world.',
                'image_link' => 'https://example.com/images/terraforming-mars.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '7 Wonders',
                'author' => 'Antoine Bauza',
                'price' => 45,
                'publish_date' => '2010-10-01',
                'url' => 'https://example.com/7-wonders',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 30,
                'AgeRange' => '10+',
                'NoOfPlayers' => '2-7',
                'Theme' => 'Civilization',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A card-drafting game where players develop ancient civilizations.',
                'image_link' => 'https://example.com/images/7-wonders.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Gloomhaven',
                'author' => 'Isaac Childres',
                'price' => 120,
                'publish_date' => '2017-04-01',
                'url' => 'https://example.com/gloomhaven',
                'status' => 'active',
                'availabilityYN' => false,
                'inventoryCount' => 0,
                'AgeRange' => '14+',
                'NoOfPlayers' => '1-4',
                'Theme' => 'Fantasy',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A massive cooperative campaign game with tactical combat.',
                'image_link' => 'https://example.com/images/gloomhaven.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Root',
                'author' => 'Cole Wehrle',
                'price' => 60,
                'publish_date' => '2018-08-01',
                'url' => 'https://example.com/root',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 13,
                'AgeRange' => '10+',
                'NoOfPlayers' => '2-4',
                'Theme' => 'Asymmetric Warfare',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'An asymmetric strategy game where woodland factions battle for control.',
                'image_link' => 'https://example.com/images/root.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pandemic',
                'author' => 'Matt Leacock',
                'price' => 40,
                'publish_date' => '2008-05-01',
                'url' => 'https://example.com/pandemic',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 25,
                'AgeRange' => '8+',
                'NoOfPlayers' => '2-4',
                'Theme' => 'Cooperative',
                'Language' => 'English',
                'discount_rate' => 0,
                'description' => 'A cooperative game where players work together to stop global outbreaks.',
                'image_link' => 'https://example.com/images/pandemic.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Crew',
                'author' => 'Thomas Sing',
                'price' => 18,
                'publish_date' => '2019-10-01',
                'url' => 'https://example.com/the-crew',
                'status' => 'active',
                'availabilityYN' => false,
                'inventoryCount' => 40,
                'AgeRange' => '10+',
                'NoOfPlayers' => '2-5',
                'Theme' => 'Space',
                'Language' => 'English',
                'discount_rate' => 3.00,
                'description' => 'A cooperative trick-taking game with 50+ missions.',
                'image_link' => 'https://example.com/images/the-crew.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Spirit Island',
                'author' => 'R. Eric Reuss',
                'price' => 80,
                'publish_date' => '2017-07-01',
                'url' => 'https://example.com/spirit-island',
                'status' => 'active',
                'availabilityYN' => false,
                'inventoryCount' => 9,
                'AgeRange' => '13+',
                'NoOfPlayers' => '1-4',
                'Theme' => 'Mythology',
                'Language' => 'English',
                'discount_rate' => 8.00,
                'description' => 'A deep cooperative game where spirits defend their island from colonizers.',
                'image_link' => 'https://example.com/images/spirit-island.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dominion',
                'author' => 'Donald X. Vaccarino',
                'price' => 45,
                'publish_date' => '2008-10-01',
                'url' => 'https://example.com/dominion',
                'status' => 'active',
                'availabilityYN' => false,
                'inventoryCount' => 17,
                'AgeRange' => '13+',
                'NoOfPlayers' => '2-4',
                'Theme' => 'Deckbuilding',
                'Language' => 'English',
                'discount_rate' => 6.00,
                'description' => 'The original deckbuilding game where players compete to build the best kingdom.',
                'image_link' => 'https://example.com/images/dominion.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Scythe',
                'author' => 'Jamey Stegmaier',
                'price' => 90,
                'publish_date' => '2016-08-01',
                'url' => 'https://example.com/scythe',
                'status' => 'active',
                'availabilityYN' => false,
                'inventoryCount' => 11,
                'AgeRange' => '14+',
                'NoOfPlayers' => '1-5',
                'Theme' => 'Dieselpunk',
                'Language' => 'English',
                'discount_rate' => 9.00,
                'description' => 'A strategy game set in an alternate-history 1920s Europe.',
                'image_link' => 'https://example.com/images/scythe.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Everdell',
                'author' => 'James A. Wilson',
                'price' => 75,
                'publish_date' => '2018-09-01',
                'url' => 'https://example.com/everdell',
                'status' => 'active',
                'availabilityYN' => false,
                'inventoryCount' => 15,
                'AgeRange' => '10+',
                'NoOfPlayers' => '1-4',
                'Theme' => 'Fantasy Woodland',
                'Language' => 'English',
                'discount_rate' => 4.50,
                'description' => 'A charming worker-placement game set in a forest kingdom.',
                'image_link' => 'https://example.com/images/everdell.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}