<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class BoardgameSeeder extends Seeder
{
    public function run()
    {
        DB::table('boardgames')->insert([
            [
                'title' => 'Silencio',
                'author' => 'Sebastiem Caiveau',
                'price' => 7,
                'publish_date' => '2020-01-01',
                'url' => 'https://example.com/silencio',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 12,
                'AgeRange' => '10+',
                'NoOfPlayers' => '2-4',
                'Theme' => 'Mystery',
                'Language' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Patchwork',
                'author' => 'Uwe Rosenberg',
                'price' => 15,
                'publish_date' => '2014-05-10',
                'url' => 'https://example.com/patchwork',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 8,
                'AgeRange' => '8+',
                'NoOfPlayers' => '2',
                'Theme' => 'Crafting',
                'Language' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cafe Fatal',
                'author' => 'Brett J. Gilbert',
                'price' => 8,
                'publish_date' => '2017-03-15',
                'url' => 'https://example.com/cafe-fatal',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 5,
                'AgeRange' => '7+',
                'NoOfPlayers' => '3-6',
                'Theme' => 'Food',
                'Language' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Overload',
                'author' => 'Wolfand Riedl',
                'price' => 20,
                'publish_date' => '2019-09-01',
                'url' => 'https://example.com/overload',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 10,
                'AgeRange' => '12+',
                'NoOfPlayers' => '2-5',
                'Theme' => 'Adventure',
                'Language' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Catan',
                'author' => 'Klaus Teuber',
                'price' => 25,
                'publish_date' => '1995-01-01',
                'url' => 'https://example.com/catan',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 20,
                'AgeRange' => '10+',
                'NoOfPlayers' => '3-4',
                'Theme' => 'Strategy',
                'Language' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ⭐ NEW ITEMS BELOW ⭐

            [
                'title' => 'Azul',
                'author' => 'Michael Kiesling',
                'price' => 30,
                'publish_date' => '2017-06-01',
                'url' => 'https://example.com/azul',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 14,
                'AgeRange' => '8+',
                'NoOfPlayers' => '2-4',
                'Theme' => 'Abstract',
                'Language' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ticket to Ride',
                'author' => 'Alan R. Moon',
                'price' => 40,
                'publish_date' => '2004-04-01',
                'url' => 'https://example.com/ticket-to-ride',
                'status' => 'active',
                'availabilityYN' => false,
                'inventoryCount' => 18,
                'AgeRange' => '8+',
                'NoOfPlayers' => '2-5',
                'Theme' => 'Travel',
                'Language' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Carcassonne',
                'author' => 'Klaus-Jürgen Wrede',
                'price' => 35,
                'publish_date' => '2000-10-01',
                'url' => 'https://example.com/carcassonne',
                'status' => 'active',
                'availabilityYN' => false,
                'inventoryCount' => 16,
                'AgeRange' => '7+',
                'NoOfPlayers' => '2-5',
                'Theme' => 'Medieval',
                'Language' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Splendor',
                'author' => 'Marc André',
                'price' => 32,
                'publish_date' => '2014-03-01',
                'url' => 'https://example.com/splendor',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 11,
                'AgeRange' => '10+',
                'NoOfPlayers' => '2-4',
                'Theme' => 'Economy',
                'Language' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Wingspan',
                'author' => 'Elizabeth Hargrave',
                'price' => 60,
                'publish_date' => '2019-03-08',
                'url' => 'https://example.com/wingspan',
                'status' => 'active',
                'availabilityYN' => true,
                'inventoryCount' => 9,
                'AgeRange' => '10+',
                'NoOfPlayers' => '1-5',
                'Theme' => 'Nature',
                'Language' => 'English',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}