services:
  - type: web
    name: laravel-boardgame
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-boardgame.onrender.com